theme: jekyll-theme-cayman
title: Autonomous Driving Intelligence Research (ADIR) Team
description: Our team was founded at ETRI in 2023. Under supervision of Prof. Dooseop Choi, various topics in the field of autonomous driving have been researched and developed. We mainly focus on motion forecasting and planning, 3D object detection and tracking, semantic segmantation.
# logo: /images/DChoi.PNG
